_format_version: "2.1"
_transform: true

plugins:
  - name: callrailhmacverify
    service: example-service
    config:
      secret: "072e77e426f92738a72fe23c4d1953b4"

services:
  - name: example-service
    url: https://mockbin.org
    routes:
      - name: jspath
        paths:
        - /
    plugins:
      - name: callrailhmacverify    
